apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deploy
  labels:
    app: calculator
spec:
  replicas: 2
  selector:
    matchlabels:
      app: calculator
  templates:
        metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: rohitrakhi/calculator:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  
